---
title: "2021 olympics"
author: "Esben Lykke Skovgaard"
date: "25/9/2021"
output:
    html_document:
      theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  cache = TRUE,
  warning = FALSE
)

library(pacman)

p_load(
  tidyverse,
  here,
  janitor,
  readxl,
  hrbrthemes,
  ggthemes,
  DT
)

theme_custom <- theme(
  legend.position = "bottom", legend.direction = "horizontal", axis.text = element_text(size = 17.8),
  plot.caption = element_text(color = "gray55", face = "bold", size = 12), legend.text = element_text(size = 17.3),
  axis.title = element_text(size = 17.8, face = "bold", color = "gray25"), legend.title = element_text(size = 17.3),
  axis.line = element_line(size = 0.45), plot.title = element_text(size = 22.1), plot.subtitle = element_text(size = 17.8),
  strip.text = element_text(size = 17.3, face = "bold")
)
```


Import data
```{r, echo=FALSE}
medals <- read_excel(here("data", "medals.xlsx")) %>%
  clean_names() %>%
  mutate(
    team_noc = factor(team_noc),
    across(where(is.character), as.numeric)
  )

athletes <-
  read_excel(here("data", "athletes.xlsx")) %>%
  clean_names()

coaches <-
  read_excel(here("data", "coaches.xlsx")) %>%
  clean_names()

gender <-
  read_excel(here("data", "entriesgender.xlsx")) %>%
  clean_names()

teams <-
  read_excel(here("data", "teams.xlsx")) %>%
  clean_names()

pop_country <-
  read_csv(here("data", "population_by_country_2020.csv")) %>%
  clean_names()

athlete_events <-
  read_csv(here("data", "athlete_events.csv")) %>%
  clean_names()

noc_regions <-
  read_csv(here("data", "noc_regions.csv")) %>%
  clean_names()

tokyoo_2021 <-
  read_csv(here("data", "Tokyo 2021 dataset.csv")) %>%
  clean_names()

# TODO list datasets in clever way
```

Total medals per country
```{r, fig.width = 18, fig.height = 25}
medals_30 <-
  medals %>%
  mutate(
    team_noc = fct_reorder(team_noc, total)
  ) %>%
  slice_max(team_noc, n = 30)

medals_30 %>%
  ggplot(aes(team_noc, total)) +
  geom_segment(aes(x = team_noc, xend = team_noc, y = 0, yend = total),
    color = if_else(medals_30$team_noc == "Denmark", "orange", "grey70"),
    size = 1.2, color = "grey70"
  ) +
  geom_point(aes(team_noc, total),
    color = if_else(medals_30$team_noc == "Denmark", "orange", "grey70"),
    size = if_else(medals_30$team_noc == "Denmark", 7, 3)
  ) +
  geom_text(aes(team_noc, total, label = if_else(team_noc == "Denmark", total, NULL)), color = "white") +
  coord_flip() +
  labs(
    y = NULL,
    x = NULL,
    title = "Toal olympic medals by country: Tokyo 2021",
    subtitle = "The medal race is topped by the usual suspects, USA and China"
  ) +
  annotate("text", x = 8, y = 40, label = "With 11 medals total,\nDenmark reached their goal of 8-10 medals", fontface = "bold") +
  annotate(
    geom = "curve", x = 9, y = 30, xend = 8, yend = 13,
    curvature = .2, arrow = arrow(length = unit(2, "mm"))
  ) +
  theme_fivethirtyeight() +
  theme_custom
```

Detailed overview in table
```{r}
medals %>%
  datatable() %>%
  formatStyle(
    columns = "gold",
    backgroundColor = "gold"
  ) %>%
  formatStyle("silver", backgroundColor = "silver") %>%
  formatStyle("bronze", backgroundColor = "orange")
```

Plot of top 10 total medals per countries compared to top 10 total medals countries per capita. Maybe a circular barplot?
```{r}
population %>%
  filter(year == 2013) %>%
  left_join(medals %>%
    rename(country = team_noc), by = "country") %>%
  drop_na() %>%
  mutate(
    medals_per_capita = (total / population) * 1e8,
    group = factor("Most medals per capita top 10")
  ) %>%
  slice_max(medals_per_capita, n = 10) %>%
  bind_rows(
    population %>%
      filter(year == 2013) %>%
      left_join(medals %>%
        rename(country = team_noc) %>%
        mutate(
          country = str_replace_all(country, c(
            "ROC" = "Russia",
            "Great Britain" = "United Kingdom of Great Britain and Northern Ireland",
            "People's Republic of China" = "China"
          ))
        ), by = "country") %>%
      drop_na() %>%
      mutate(
        medals_per_capita = (total / population) * 1e8,
        group = factor("Medals total top 10 countries")
      ) %>%
      slice_min(rank_by_total, n = 10)
  ) %>%
  group_by(group) %>% 
  mutate(country = fct_reorder(country, medals_per_capita)) %>% 
  ggplot(aes(country, medals_per_capita, fill = group)) +
  geom_col(position = "dodge", color = "black", alpha = .5) + 
  coord_polar() + 
  theme_fivethirtyeight() +
  scale_fill_tableau(palette = "Jewel Bright") +
  scale_y_log10() +
  labs(fill = NULL,
       title = "Medal per capita",
       subtitle = "Comparison between the top 10 countries based on total medals and top 10 countries based on most medals per capita")

# TODO overvej også at smide Danmark ind i plottet
```
